CREATE TABLE [dbo].[tbUsuario]
(
	[CPF] NVARCHAR(11) NOT NULL
	,[Nome] NVARCHAR(200) NOT NULL
	,[Email] NVARCHAR(200) NOT NULL
	,[Login] NVARCHAR(200) NOT NULL
	,[Senha] BINARY(64) NOT NULL,

	CONSTRAINT [PK_tbUsuario_CPF] PRIMARY KEY ([CPF])
)
